
# COMBINES INDIVIDUAL TABLES INTO A LARGE TABLE
# USED EVERYTIME GENERAL FUNCTIONS ARE CALLED


from astropy.io import ascii as asc
from astropy.table import hstack

# This code stacks ascii flux tables generated by the zoom_and_gauss_general code into a large ascii file


def h_stack(fitspath, table_files, asc_intro, new_name):
    '''
    Purpose

    Parameters

    fitspath
    table_files
    asc_intro
    new_name

    Returns

    Outputs

    '''
    table_files.sort()
    for ii in range(len(table_files)):
        asc_tab = asc.read(table_files[ii])
        if ii == 0: 
            hstacking = hstack([asc_intro, asc_tab])
        else:
            hstacking = hstack([hstacking, asc_tab])

        print(type(hstacking))
    # Grid Fits Files
    # hstacking.write(new_name, format='fits')
    # Grid Ascii Files
    asc.write(hstacking, new_name, format='fixed_width_two_line', overwrite=True)
